# Generated by Django 5.2.4 on 2026-09-25 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basebox', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='errorlog',
            name='user',
        ),
    ]
