# Generated by Django 5.2.4 on 2026-09-24 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('arxiv_id', models.CharField(help_text='arXiv identifier without the version suffix, e.g. 2409.01234', max_length=64, unique=True)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('title', models.TextField()),
                ('abstract', models.TextField()),
                ('published', models.DateTimeField(db_index=True)),
                ('updated', models.DateTimeField(db_index=True)),
                ('doi', models.CharField(blank=True, max_length=255, null=True)),
                ('journal_ref', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('abs_url', models.URLField(blank=True, max_length=255)),
                ('pdf_url', models.URLField(blank=True, max_length=255)),
                ('content_hash', models.CharField(help_text='SHA-256 of title + abstract; used to detect when the embedding is stale', max_length=64)),
                ('categories', models.ManyToManyField(related_name='papers', to='papers.category')),
                ('primary_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primary_papers', to='papers.category')),
            ],
            options={
                'ordering': ['-published'],
            },
        ),
        migrations.CreateModel(
            name='PaperAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorships', to='papers.author')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorships', to='papers.paper')),
            ],
            options={
                'ordering': ['paper', 'position'],
            },
        ),
        migrations.AddField(
            model_name='paper',
            name='authors',
            field=models.ManyToManyField(related_name='papers', through='papers.PaperAuthor', to='papers.author'),
        ),
        migrations.AddConstraint(
            model_name='paperauthor',
            constraint=models.UniqueConstraint(fields=('paper', 'position'), name='uniq_paper_author_position'),
        ),
        migrations.AddConstraint(
            model_name='paperauthor',
            constraint=models.UniqueConstraint(fields=('paper', 'author'), name='uniq_paper_author'),
        ),
    ]
