# Generated by Django 5.2.4 on 2026-09-24 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('papers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperEmbedding',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('paper', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='embedding', serialize=False, to='papers.paper')),
                ('embedding', models.BinaryField()),
                ('model', models.CharField(db_index=True, max_length=100)),
                ('content_hash', models.CharField(max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
