# Generated by Django 5.2.4 on 2026-09-24 18:15

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('papers', '0001_initial'),
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='PaperEmbedding',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('paper', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='embedding', serialize=False, to='papers.paper')),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1536)),
                ('model', models.CharField(max_length=100)),
                ('content_hash', models.CharField(max_length=64)),
            ],
            options={
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='paper_embedding_hnsw', opclasses=['vector_cosine_ops'])],
            },
        ),
    ]
